# Generated by Django 4.2.24 on 2025-09-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lti_store", "0002_add_lti_1p3_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externallticonfiguration",
            name="lti_1p3_public_jwk",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Platform's generated JWK keyset. This will be generated automatically, no need to fill out.",
                verbose_name="LTI 1.3 Public JWK",
            ),
        ),
    ]
