# Generated by Django 4.2.21 on 2025-09-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lti_store", "0002_add_lti_1p3_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="externallticonfiguration",
            name="lti_1p1_client_key",
            field=models.CharField(
                blank=True,
                help_text="Client key provided by the LTI tool provider.",
                max_length=255,
                verbose_name="LTI 1.1 Client Key",
            ),
        ),
        migrations.AlterField(
            model_name="externallticonfiguration",
            name="lti_1p1_client_secret",
            field=models.CharField(
                blank=True,
                help_text="Client secret provided by the LTI tool provider.",
                max_length=255,
                verbose_name="LTI 1.1 Client Secret",
            ),
        ),
        migrations.AlterField(
            model_name="externallticonfiguration",
            name="lti_1p1_launch_url",
            field=models.CharField(
                blank=True,
                help_text="The URL of the external tool that initiates the launch.",
                max_length=255,
                verbose_name="LTI 1.1 Launch URL",
            ),
        ),
    ]
